version: '3'
services:
  elasticsearch:
    image: elasticsearch:6.4.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:6.4.1
    ports:
      - 5601:5601
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
#      - PGDATA=/postgres
    ports:
      - 5432:5432
